"""
Pydantic models for API requests and responses.
"""
from datetime import datetime
from typing import Optional, List
from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """Request model for chat endpoint."""
    message: str = Field(..., min_length=1, description="User's message to the assistant")
    session_id: Optional[str] = Field(None, description="Optional session ID for conversation history")


class ChatResponse(BaseModel):
    """Response model for chat endpoint."""
    response: str = Field(..., description="Assistant's response")
    model: str = Field(..., description="LLM model used for generation")


class StructuredChatRequest(BaseModel):
    """Request model for structured chat endpoint."""
    message: str = Field(..., min_length=1, description="User's message to the assistant")


class StructuredAnswer(BaseModel):
    """Structured response payload generated by the assistant."""
    summary: str = Field(..., description="Concise answer summary")
    key_points: list[str] = Field(default_factory=list, description="Important supporting points")
    recommendations: list[str] = Field(default_factory=list, description="Actionable next steps")
    risks: list[str] = Field(default_factory=list, description="Risks or caveats to consider")
    confidence: float = Field(..., ge=0.0, le=1.0, description="Model confidence score between 0 and 1")


class StructuredChatResponse(BaseModel):
    """API response model for structured chat endpoint."""
    output: StructuredAnswer
    model: str = Field(..., description="LLM model used for generation")


# Session Management Models

class SessionCreate(BaseModel):
    """Request to create a new session."""
    metadata: Optional[dict] = Field(default_factory=dict, description="Optional metadata for the session")


class MessageResponse(BaseModel):
    """A message in conversation history."""
    role: str
    content: str
    timestamp: datetime


class SessionResponse(BaseModel):
    """Response model for session details."""
    session_id: str
    created_at: datetime
    updated_at: datetime
    message_count: int
    metadata: dict


class SessionListResponse(BaseModel):
    """Response model for listing sessions."""
    sessions: List[SessionResponse]
    total: int


class HistoryResponse(BaseModel):
    """Response model for conversation history."""
    session_id: str
    messages: List[MessageResponse]
    total: int


# Document Management Models

class DocumentUploadResponse(BaseModel):
    """Response after successful document upload."""
    document_id: str = Field(..., description="Unique document identifier")
    filename: str = Field(..., description="Original filename")
    file_type: str = Field(..., description="File type (pdf, txt, docx)")
    file_size: int = Field(..., description="File size in bytes")
    chunks_created: int = Field(..., description="Number of chunks created")
    upload_date: datetime = Field(..., description="Upload timestamp")


class DocumentResponse(BaseModel):
    """Response model for document metadata."""
    document_id: str
    filename: str
    upload_date: str
    total_chunks: int


class DocumentListResponse(BaseModel):
    """Response model for listing documents."""
    documents: List[DocumentResponse]
    total: int


class ChunkResponse(BaseModel):
    """Response model for a document chunk."""
    chunk_id: str = Field(..., description="Unique chunk identifier")
    text: str = Field(..., description="Chunk text content")
    chunk_index: int = Field(..., description="Index of this chunk in the document")
    metadata: dict = Field(default_factory=dict, description="Chunk metadata")


class DocumentChunksResponse(BaseModel):
    """Response model for listing document chunks."""
    document_id: str
    chunks: List[ChunkResponse]
    total: int


class VectorStoreStatsResponse(BaseModel):
    """Response model for vector store statistics."""
    total_documents: int
    total_chunks: int
    collection_name: str


# Semantic Search Models (Feature 5)

class SearchRequest(BaseModel):
    """Request model for semantic search over indexed documents."""
    query: str = Field(..., min_length=1, description="Natural language search query")
    top_k: int = Field(5, ge=1, le=20, description="Number of results to return")
    document_id: Optional[str] = Field(None, description="Optional: scope search to a single document")


class SearchResult(BaseModel):
    """A single ranked search result."""
    chunk_id: str = Field(..., description="Unique chunk identifier")
    text: str = Field(..., description="Matched chunk text")
    score: float = Field(..., ge=0.0, le=1.0, description="Similarity score (higher = more similar)")
    document_id: str = Field(..., description="Source document identifier")
    filename: str = Field(..., description="Source document filename")
    chunk_index: int = Field(..., description="Index of this chunk within its document")


class SearchResponse(BaseModel):
    """Response model for semantic search results."""
    query: str
    results: List[SearchResult]
    total: int
